apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jk3ghw2gy-nodejs 
  janus-idp.io/tekton: jk3ghw2gy-nodejs
  backstage.io/kubernetes-id: jk3ghw2gy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jk3ghw2gy-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  