apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jk3ghw2gy-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jk3ghw2gy-nodejs 
  name: jk3ghw2gy-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jk3ghw2gy-nodejs 
